name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        
    - name: Install Node.js dependencies
      working-directory: ./Client
      run: npm install
      
    - name: Lint Python code
      run: |
        flake8 Src/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 Src/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Type check Python code
      run: mypy Src/ --ignore-missing-imports
      
    - name: Lint JavaScript code  
      working-directory: ./Client
      run: npm run lint
      
    - name: Run Python tests
      run: pytest tests/ -v --cov=Src/ --cov-report=xml
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run security scan on Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety
        safety check -r requirements.txt
        
    - name: Run security scan on Node.js dependencies
      working-directory: ./Client
      run: |
        npm install
        npm audit --audit-level=high
        
  build-and-validate:
    runs-on: ubuntu-latest
    needs: [lint-and-test]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install CDK
      run: npm install -g aws-cdk
      
    - name: Install infrastructure dependencies
      working-directory: ./infrastructure
      run: npm install
      
    - name: CDK Synth
      working-directory: ./infrastructure
      run: cdk synth
      
    - name: Build client assets
      working-directory: ./Client
      run: |
        npm install
        npm run build
